"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

from django.conf.locale.ru import(
     formats as ru_formats
     )

from .settings_sec import *
from .settings_sec import (
    DB_ENGINE_PG,
    DB_NAME_PG,
    DB_USER_PG,
    DB_PASSWORD_PG,
    DB_HOST_PG,
    DB_PORT_PG
)

from .settings_rest_framework import (
     REST_FRAMEWORK as REST_FRAMEWORK_SETTINGS
)

from .settings_intalled_apps import (
    INSTALLED_APPS as INSTALLED_APPS_SETTINGS
)

# from .settings_sec import DATABASES_SEC

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Перенес

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = INSTALLED_APPS_SETTINGS


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# добавляется ручками
REST_FRAMEWORK = REST_FRAMEWORK_SETTINGS

# настройки simpleJWT
SIMPLE_JWT={  #
    # Время жизни access_tpken
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    
    # Время жизни refresh_token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    
    # обновлять refresh_token при каждом запросе
    'ROTATE_REFRESH_TOKENS': False,
    
    # Добавлять старые reffresh_tokens в черный список
    'BLACKLIST_AFTER_ROTATION': True
}


ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'sqlite': {
        'ENGINE': DB_ENGINE,
        'NAME': DB_NAME,
    },

    'default': {
        'ENGINE': DB_ENGINE_PG,
        'NAME': DB_NAME_PG,
        'USER': DB_USER_PG,
        'PASSWORD': DB_PASSWORD_PG,
        'HOST': DB_HOST_PG,
        'PORT': DB_PORT_PG ,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Yekaterinburg'

ru_formats.DATETIME_FORMAT = "d.M.Y H:i:s"
# ru_formats.date

# ru_formats.DATE_FORMAT = 'd.m.Y'
# ru_formats.TIME_FORMAT = 'H:i'
# ru_formats.DATETIME_FORMAT = 'd.m.Y, H:i'

# ru_formats.DATETIME_INPUT_FORMATS = [
#     '%d.%m.%Y, %H:%M:%S',
#     '%d.%m.%Y, %H:%M',
# ]


USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
