# Generated by Django 5.1.5 on 2025-01-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='сompleted_date',
            field=models.DurationField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
